---
spring:
  application:
    name: eureka-service

server:
  port: ${EUREKA_SERVICE_PORT:8181}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    region: region1
    serviceUrl:
      zone1: http://localhost:8181/eureka/
    availability-zones:
      region1: zone1
  instance:
    hostname: localhost
    metadata-map:
      zone: zone1
  server:
    renewal-percent-threshold: 0.85